name: my_portfolio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts:
  flutter_bloc: 6.0.2
  freezed_annotation: 0.11.0
  injectable: 1.0.2
  get_it: 4.0.4
  json_serializable: 3.4.1
  json_annotation: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  freezed: 0.11.4
  injectable_generator: 1.0.2

dependency_overrides:
  analyzer: '0.39.14'


flutter:
  uses-material-design: true
  assets:
    - assets/json/user_data.json
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
